### PR TITLE
tv-show-dom-project-for review

### PR DESCRIPTION
**Pull request by RitaGlushkova**

### CODE REVIEW

**Comment by RitaGlushkova** [comment]
@DiegoJunior0 level 400 commit is ready for review

**Review by DiegoJunior0 — APPROVED** [review]
This all looks great, well done!

**Comment by RitaGlushkova** [comment]
@DiegoJunior0 Hi henry, my project is ready for review, I need to merge it to main after your review so that it gets updated on my deployed website

**Review by DiegoJunior0 — APPROVED** [review]
All looks great. Well done!

**Pull request merged**
